# Generated by Django 5.2.15 on 2026-06-24 12:27

import apps.orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(db_index=True, default=apps.orders.models._order_number, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('created', 'Ожидает оплаты'), ('paid', 'Оплачен, передан в обработку'), ('sent_to_producer', 'Передан производителю'), ('assembling', 'Собирается'), ('shipped', 'Отправлен'), ('in_transit', 'В пути'), ('ready_for_pickup', 'Ожидает в пункте выдачи'), ('delivered', 'Доставлен'), ('completed', 'Заказ завершён'), ('cancelled', 'Отменён')], db_index=True, default='created', max_length=24)),
                ('ship_full_name', models.CharField(max_length=255)),
                ('ship_phone', models.CharField(max_length=32)),
                ('ship_city', models.CharField(max_length=128)),
                ('ship_address', models.CharField(max_length=512)),
                ('ship_postal_code', models.CharField(blank=True, max_length=16)),
                ('goods_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tenants.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('producer_payout_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('seller_markup_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tenants.producer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.storeproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(max_length=24)),
                ('actor_type', models.CharField(choices=[('system', 'Система'), ('buyer', 'Покупатель'), ('seller', 'Продавец'), ('producer', 'Производитель'), ('carrier', 'Служба доставки'), ('admin', 'Суперадмин')], max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=512)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Ожидает сборки'), ('assembling', 'Собирается'), ('shipped', 'Отправлена'), ('in_transit', 'В пути'), ('delivered', 'Доставлена'), ('cancelled', 'Отменена')], db_index=True, default='pending', max_length=16)),
                ('delivery_provider', models.CharField(blank=True, max_length=32)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tracking_number', models.CharField(blank=True, max_length=64)),
                ('tracking_url', models.URLField(blank=True)),
                ('last_carrier_status', models.CharField(blank=True, max_length=64)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='tenants.producer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status'], name='orders_orde_buyer_i_4389c9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status'], name='orders_orde_store_i_610c63_idx'),
        ),
    ]
