# Generated by Django 5.2.15 on 2026-06-24 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeraddress',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Магазин, к которому привязан покупатель (опционально)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_addresses', to='tenants.store'),
        ),
        migrations.AddField(
            model_name='buyeraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('auth_provider', 'external_id'), name='uniq_provider_external_id'),
        ),
    ]
