# Generated by Django 5.2.15 on 2026-06-24 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payee_type', models.CharField(choices=[('seller', 'Продавец'), ('producer', 'Производитель')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('paid', 'Выплачено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16)),
                ('requisites_snapshot', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=512)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='orders.order')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='tenants.producer')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='tenants.store')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('store__isnull', False)), fields=('order', 'payee_type', 'store'), name='uniq_seller_payout'), models.UniqueConstraint(condition=models.Q(('producer__isnull', False)), fields=('order', 'payee_type', 'producer'), name='uniq_producer_payout')],
            },
        ),
    ]
