# Generated by Django 5.2.15 on 2026-06-24 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('inn', models.CharField(blank=True, max_length=32, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=32, verbose_name='ОГРН/ОГРНИП')),
                ('main_category', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждён'), ('blocked', 'Заблокирован')], db_index=True, default='pending', max_length=16)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('payout_requisites', models.JSONField(blank=True, default=dict)),
                ('blocked_reason', models.CharField(blank=True, max_length=255)),
                ('categories', models.ManyToManyField(blank=True, help_text='До 3 категорий продукции производителя', related_name='producers', to='catalog.category')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('niche', models.CharField(choices=[('clothing', 'Одежда и обувь'), ('electronics', 'Электроника'), ('home', 'Товары для дома'), ('beauty', 'Красота и здоровье'), ('food', 'Продукты питания'), ('kids', 'Детские товары'), ('other', 'Прочее')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('blocked', 'Заблокирован')], db_index=True, default='draft', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='stores/banners/')),
                ('theme', models.CharField(default='default', max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('inn', models.CharField(blank=True, max_length=32, verbose_name='ИНН/ОГРНИП')),
                ('payout_requisites', models.JSONField(blank=True, default=dict)),
                ('blocked_reason', models.CharField(blank=True, max_length=255)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopIntegration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('store', 'Магазин'), ('producer', 'Производитель')], max_length=16)),
                ('kind', models.CharField(choices=[('payment', 'Оплата'), ('delivery', 'Доставка')], max_length=16)),
                ('provider', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('not_connected', 'Не подключено'), ('active', 'Активно'), ('error', 'Ошибка подключения')], default='not_connected', max_length=16)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('last_error', models.CharField(blank=True, max_length=512)),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='tenants.producer')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='tenants.store')),
            ],
            options={
                'ordering': ['kind', 'provider'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('store__isnull', False)), fields=('store', 'kind', 'provider'), name='uniq_store_integration'), models.UniqueConstraint(condition=models.Q(('producer__isnull', False)), fields=('producer', 'kind', 'provider'), name='uniq_producer_integration')],
            },
        ),
    ]
